<?php
/**
 * Created by PhpStorm.
 * User: jonas.wrede
 * Date: 16.09.18
 * Time: 04:01
 */

include "local.php";

class TSDb extends mysqli{


    public $connect;

     /**
      * @return mysqli
      */
     public function __construct(array $a){


         $this->connect = mysqli_connect($a["host_name"],$a["user_name"],$a["password"],$a["database"]);

         return $this->connect;

    }


     /**
      * @param string $username
      * @return bool|mysqli_result
      */

     public function select_user($username){

         $username = $this->connect->real_escape_string($username);
         $query = "SELECT lname,pass,id_group,id_user from login,user_to_group where lname= '" . $username. "' AND login.id = user_to_group.id_user";
         $result = $this->connect->query($query);

         return $result;
     }


    /**
     * @return bool
     */
     public function close()
     {
        return $this->connect->close();// TODO: Change the autogenerated stub

     }
}