<?php
/**
 * Created by PhpStorm.
 * User: jonas.wrede
 * Date: 16.09.18
 * Time: 04:01
 */

include "local.php";

class TSDb extends mysqli{

    public $host_name = 'db748804796.db.1and1.com';
    public $database = 'db748804796';
    public $user_name = 'dbo748804796';
    public $password = 'Tml321Bmg()=';

    public $connect;

     /**
      * @return mysqli
      */
     public function __construct(){

         $this->connect = mysqli_connect($this->host_name,$this->user_name,$this->password,$this->database);

         return $this->connect;

    }


     /**
      * @param string $username
      * @return bool|mysqli_result
      */

     public function select_user($username){

         $username = $this->connect->real_escape_string($username);
         $query = "SELECT lname,pass,id_group,id_user from login,user_to_group where lname= '" . $username. "' AND login.id = user_to_group.id_user";
         $result = $this->connect->query($query);

         return $result;
     }


    /**
     * @return bool
     */
     public function close()
     {
        return $this->connect->close();// TODO: Change the autogenerated stub

     }
}